import type { City } from "./types";

const U = "2026-10-05";

// Wave 3 (2026-10-05): high-value metros outside Greater Houston, chosen from LeadSmart roofing payout and coverage.
// ZIPs are covered ZIPs from src/data/coverage-zips.json (first 30 shown). Copy is written per city, never templated.
export const citiesMore: City[] = [
  {
    slug: "dallas", name: "Dallas", stateSlug: "texas", county: "Dallas", region: "dfw", status: "PUBLISHED", officeAddress: null,
    zips: ["75201", "75202", "75203", "75204", "75205", "75206", "75208", "75209", "75214", "75218", "75219", "75220", "75223", "75224", "75225", "75226", "75228", "75229", "75230", "75231"],
    areas: ["M Streets", "Lakewood", "Lake Highlands", "Preston Hollow", "Oak Cliff", "Kessler Park", "Bishop Arts", "North Dallas", "East Dallas", "Uptown"],
    intro: "Dallas sits in one of the most hail-damaged metro areas in the country, and roof replacements after spring storms are routine across the city. Housing runs from 1920s Tudors in the M Streets and Craftsman bungalows in Oak Cliff to 1960s ranches in Lake Highlands and large newer homes in Preston Hollow and North Dallas.",
    housingNotes: "Older East Dallas and Oak Cliff homes often have steep, complex roofs with dormers, plank decking and decades of re-roofs underneath. Postwar ranches in Lake Highlands and North Dallas have long, low roofs that catch hail across wide slopes. Many Uptown and Oak Lawn townhomes have flat roof decks.",
    localIssues: [
      { title: "Hail season", body: "March through June brings the most hail to Dallas. After a storm, dented gutters, vents and AC fins are the quickest clue that the shingles were hit too. Many owners now choose [Class 4 shingles](/roofing-services/impact-resistant-shingles/) at replacement." },
      { title: "Tornado and wind damage", body: "The October 2019 tornado tore through North Dallas and Preston Hollow, a reminder that severe wind is a real risk alongside hail. Wind-rated installation with correct nailing and starter strips holds up better." },
      { title: "Historic and conservation districts", body: "Neighborhoods such as Swiss Avenue, Munger Place and parts of Oak Cliff are historic or conservation districts where visible roofing changes can need city review. Check before switching materials." },
    ],
    popularServices: ["hail-damage-roof-repair", "impact-resistant-shingles", "roof-replacement", "roof-insurance-claims", "storm-damage-roof-repair"],
    nearby: ["fort-worth"],
    storm: "Dallas is far from the coastal windstorm area; hail and straight-line wind drive most claims. Many policies carry a percentage-based wind and hail deductible, so check yours before storm season.",
    permits: "The City of Dallas issues building permits through Development Services, including for many re-roofs. Ask the contractor to confirm and pull the permit, and check historic or conservation district rules if they apply.",
    faqs: [
      { q: "How often does hail damage roofs in Dallas?", a: "Damaging hail hits parts of the Dallas area most years, usually in spring. A roof that's 10 or more years old in Dallas has often already been through several hail events." },
      { q: "Do I need a permit to replace my roof in Dallas?", a: "Often yes. The City of Dallas issues permits for roofing work; the contractor should confirm the requirement and pull the permit." },
    ],
    updated: U,
  },
  {
    slug: "fort-worth", name: "Fort Worth", stateSlug: "texas", county: "Tarrant", region: "dfw", status: "PUBLISHED", officeAddress: null,
    zips: ["76102", "76103", "76104", "76105", "76107", "76108", "76109", "76110", "76111", "76112", "76114", "76116", "76118", "76120", "76123", "76126", "76131", "76132", "76133", "76134"],
    areas: ["Fairmount", "Arlington Heights", "Tanglewood", "TCU area", "Ryan Place", "Westover Hills border", "Alliance", "Benbrook border", "Wedgwood", "Eastchase"],
    intro: "Fort Worth shares the Dallas-Fort Worth hail corridor and has a long history of severe storms, including the 1995 Mayfest hailstorm that dropped softball-size hail on crowds downtown. Its housing ranges from early 20th-century bungalows in Fairmount and Ryan Place to fast-growing subdivisions around Alliance in far north Fort Worth.",
    housingNotes: "Near Southside and Fairmount homes are older frame bungalows with steep roofs and porches tied into the main roof. Arlington Heights and the TCU area have brick homes from the 1920s through the 1950s. Far north and southwest Fort Worth is full of newer two-story homes with builder-grade roofs.",
    localIssues: [
      { title: "Hail in the DFW corridor", body: "Spring storms that form west of the city often hit Fort Worth first. Checking soft metals and getting an inspection after each major storm keeps claims within policy deadlines." },
      { title: "Historic districts", body: "Fairmount is one of the largest historic districts in the Southwest. Visible exterior changes there can need review by the city's historic preservation staff, so plan material changes in advance." },
      { title: "New construction on the north side", body: "Rapid growth around Alliance and north Fort Worth means many first-generation roofs. An [inspection](/roofing-services/roof-inspection/) before builder warranties expire can catch nailing and flashing shortcuts." },
    ],
    popularServices: ["hail-damage-roof-repair", "roof-replacement", "roof-inspection", "impact-resistant-shingles", "roof-repair"],
    nearby: ["dallas"],
    storm: "Fort Worth is inland, outside the coastal windstorm area. Hail is the leading cause of roof claims, followed by straight-line wind and tornadoes.",
    permits: "The City of Fort Worth Development Services Department issues building permits, including for roofing work. Confirm historic district requirements in Fairmount and other designated areas.",
    faqs: [
      { q: "Are impact-resistant shingles worth it in Fort Worth?", a: "Often. Hail is frequent, and Texas insurers commonly discount premiums for Class 4 roofs. Ask your insurer for the discount before deciding." },
      { q: "Can I replace my roof in the Fairmount historic district?", a: "Yes, but visible material or style changes may need review. The contractor can help with the application." },
    ],
    updated: U,
  },
  {
    slug: "san-antonio", name: "San Antonio", stateSlug: "texas", county: "Bexar", region: "south-central", status: "PUBLISHED", officeAddress: null,
    zips: ["78201", "78202", "78203", "78204", "78205", "78207", "78208", "78209", "78210", "78212", "78213", "78216", "78217", "78218", "78220", "78223", "78228", "78229", "78230", "78232"],
    areas: ["King William", "Monte Vista", "Tobin Hill", "Olmos Park border", "Stone Oak", "Medical Center", "Leon Valley border", "Southtown", "Dellview", "Northwood"],
    intro: "San Antonio's April 2016 hailstorm, one of the costliest in Texas history, sent large hail across the north and northwest sides and led to tens of thousands of roof claims. The city's housing spans 19th-century homes in King William, early 20th-century homes in Monte Vista and large newer subdivisions in Stone Oak and the far north side.",
    housingNotes: "Historic homes near downtown have steep roofs, metal roofing in places, and masonry or stucco walls that need careful flashing. Mid-century ranches across the north central area have wide, low roofs. Newer north-side homes have architectural shingles and HOA color rules.",
    localIssues: [
      { title: "Hail on the north side", body: "The 2016 storm showed how much damage hail can do to San Antonio's north and northwest neighborhoods. [Hail damage inspections](/roofing-services/hail-damage-roof-repair/) after spring storms are worth the time." },
      { title: "Heat and UV", body: "Long, hot summers dry out shingles and sealants. Balanced attic ventilation and lighter shingle colors where HOAs allow help roofs last between storms." },
      { title: "Historic districts", body: "King William, Monte Vista and other historic districts require review of visible exterior changes through the city's Office of Historic Preservation." },
    ],
    popularServices: ["hail-damage-roof-repair", "roof-replacement", "roof-ventilation", "impact-resistant-shingles", "roof-insurance-claims"],
    nearby: ["austin"],
    storm: "San Antonio is inland, outside the coastal windstorm area. Hail and severe thunderstorms cause most claims, and flash flooding can affect access after storms.",
    permits: "The City of San Antonio Development Services Department issues building permits. Historic districts add review through the Office of Historic Preservation. Many surrounding areas are separate cities or unincorporated Bexar County with their own rules.",
    faqs: [
      { q: "What should I do after a hailstorm in San Antonio?", a: "Check gutters, vents and AC units for dents, photograph damage from the ground, and get an inspection before filing a claim." },
      { q: "Is Alamo Heights part of San Antonio for permits?", a: "No. Alamo Heights, Olmos Park and several other enclaves are separate cities with their own permit offices." },
    ],
    updated: U,
  },
  {
    slug: "austin", name: "Austin", stateSlug: "texas", county: "Travis", region: "south-central", status: "PUBLISHED", officeAddress: null,
    zips: ["78701", "78702", "78703", "78704", "78705", "78721", "78722", "78723", "78726", "78727", "78729", "78730", "78731", "78732", "78733", "78735", "78745", "78746", "78748", "78749"],
    areas: ["Hyde Park", "Travis Heights", "Clarksville", "Tarrytown", "Allandale", "Mueller", "Circle C", "Westlake border", "Barton Hills", "Crestview"],
    intro: "Austin roofs face spring hail, intense summer heat, and wildfire risk on the city's wooded west side, where Austin adopted a wildland-urban interface code. Housing ranges from early 20th-century bungalows in Hyde Park and Travis Heights to 1950s ranches in Allandale and Crestview and newer homes in Mueller and Circle C.",
    housingNotes: "Central Austin bungalows often have older plank decking and tight attics with little ventilation. Hill Country homes west of MoPac sit on slopes under oaks and cedar. Many newer infill homes add metal roofing or low-slope sections.",
    localIssues: [
      { title: "Wildfire-zone roofing", body: "Austin's wildland-urban interface code applies to many west-side and hill-country neighborhoods and generally calls for Class A roofing and ember-resistant construction. See [wildfire-resistant roofing](/resources/wildfire-resistant-roofing/)." },
      { title: "Ice storms and falling limbs", body: "The February 2023 ice storm brought down huge numbers of tree limbs across Austin, many onto roofs. Trimming oaks back from the roof reduces damage in ice and wind events." },
      { title: "Hail", body: "Spring storms bring damaging hail to Austin and its suburbs, and many roofs have been replaced after hail claims." },
    ],
    popularServices: ["storm-damage-roof-repair", "metal-roofing", "hail-damage-roof-repair", "roof-ventilation", "roof-replacement"],
    nearby: ["san-antonio"],
    storm: "Austin is inland, outside the coastal windstorm area. Hail, wind, ice storms and wildfire are the main roof risks.",
    permits: "The City of Austin Development Services Department issues permits, and the wildland-urban interface code adds requirements in designated areas. Surrounding cities such as Round Rock and West Lake Hills have their own rules.",
    faqs: [
      { q: "Does my Austin home need a Class A roof?", a: "If it's in an area covered by Austin's wildland-urban interface code, new roofs and many re-roofs generally must be Class A. The contractor or city can confirm for your address." },
      { q: "Are metal roofs common in Austin?", a: "Yes. They suit the heat, resist embers and hold up well in wind, and they're common on newer and Hill Country homes." },
    ],
    updated: U,
  },
  {
    slug: "denver", name: "Denver", stateSlug: "colorado", county: "Denver", region: "front-range", status: "PUBLISHED", officeAddress: null,
    zips: ["80202", "80203", "80204", "80205", "80206", "80207", "80209", "80210", "80211", "80212", "80216", "80218", "80219", "80220", "80222", "80223", "80224", "80230", "80231", "80238"],
    areas: ["Capitol Hill", "Highland", "Washington Park", "Park Hill", "Congress Park", "Baker", "Sloan's Lake", "Central Park", "Hampden", "Green Valley Ranch"],
    intro: "Denver roofs take some of the most frequent hail in the country, along with intense high-altitude sun and snow that can arrive from September through May. Housing runs from 1890s Victorians and Denver Squares in Capitol Hill and Highland to postwar ranches in Harvey Park and new construction in Central Park and Green Valley Ranch.",
    housingNotes: "Older central neighborhoods have steep roofs with dormers, masonry chimneys and sometimes slate or several shingle layers. Postwar ranches have long, low roofs that take hail across wide slopes. Newer east-side homes have architectural shingles that are now being replaced after hail claims.",
    localIssues: [
      { title: "Hail and Class 4 roofs", body: "Hail claims are a fact of life in Denver. Many owners choose [Class 4 impact-resistant shingles](/roofing-services/impact-resistant-shingles/) at replacement, and Colorado insurers often discount them." },
      { title: "Sun at altitude", body: "At over 5,000 feet, ultraviolet light breaks down shingles, sealants and pipe boots faster than at sea level. Expect to replace boots and reseal flashing more often." },
      { title: "Snow and ice dams", body: "Spring and fall snowstorms are heavy and wet, and freeze-thaw cycles cause ice dams on older homes with little insulation." },
    ],
    popularServices: ["hail-damage-roof-repair", "impact-resistant-shingles", "roof-replacement", "ice-dam-removal", "roof-insurance-claims"],
    nearby: ["colorado-springs"],
    storm: "Hail is Denver's leading roof risk. Colorado law prohibits roofing contractors from paying or waiving your deductible and sets specific rules for roofing contracts on insurance claims.",
    permits: "Denver requires a roofing permit for re-roofs and licenses roofing contractors. Landmark districts can add design review for visible changes.",
    faqs: [
      { q: "Does Denver require a permit for a new roof?", a: "Yes. Re-roofs need a permit, and the contractor must hold the appropriate Denver license." },
      { q: "Can a Denver roofer cover my insurance deductible?", a: "No. Colorado law prohibits roofing contractors from paying, waiving or rebating your deductible." },
    ],
    updated: U,
  },
  {
    slug: "colorado-springs", name: "Colorado Springs", stateSlug: "colorado", county: "El Paso", region: "front-range", status: "PUBLISHED", officeAddress: null,
    zips: ["80903", "80904", "80905", "80906", "80907", "80909", "80910", "80911", "80915", "80916", "80917", "80918", "80919", "80920", "80921", "80922", "80923", "80924", "80925", "80927"],
    areas: ["Old Colorado City", "Broadmoor", "Briargate", "Rockrimmon", "Mountain Shadows", "Old North End", "Powers corridor", "Northgate", "Stratton Meadows", "Cheyenne Mountain area"],
    intro: "Colorado Springs roofs face frequent hail, strong downslope winds off Pikes Peak, heavy spring snow and serious wildfire risk along the foothills, where the Waldo Canyon fire in 2012 and the Black Forest fire in 2013 destroyed hundreds of homes. Housing ranges from Victorian homes in the Old North End to large newer subdivisions on the north and east sides.",
    housingNotes: "Foothill neighborhoods such as Mountain Shadows, Rockrimmon and the Broadmoor area sit at the wildland edge on sloped lots. North and east-side subdivisions built since the 1990s have architectural shingles frequently replaced after hail.",
    localIssues: [
      { title: "Wildfire on the west side", body: "Homes along the foothills benefit from Class A roofing and ember-resistant vents. After Waldo Canyon, many rebuilt homes in Mountain Shadows used fire-resistant roofing." },
      { title: "Hail", body: "Colorado Springs sees frequent damaging hail. [Hail damage inspections](/roofing-services/hail-damage-roof-repair/) and Class 4 shingles are common." },
      { title: "Downslope winds", body: "Strong winds off the mountains lift shingle edges and ridge caps; correct nailing and starter strips matter." },
    ],
    popularServices: ["hail-damage-roof-repair", "metal-roofing", "impact-resistant-shingles", "wind-damage-roof-repair", "roof-replacement"],
    nearby: ["denver"],
    storm: "Hail, wind and wildfire are the main roof risks. Colorado's roofing-contract law applies to insurance work, including the ban on contractors paying or waiving deductibles.",
    permits: "The Pikes Peak Regional Building Department issues permits and licenses contractors, including roofers, for Colorado Springs and much of El Paso County.",
    faqs: [
      { q: "Who licenses roofers in Colorado Springs?", a: "The Pikes Peak Regional Building Department licenses contractors and issues roofing permits. You can verify a license with PPRBD." },
      { q: "What roof is best near the foothills?", a: "A Class A rated assembly, such as Class A shingles or metal, with ember-resistant vents and clean gutters." },
    ],
    updated: U,
  },
  {
    slug: "oklahoma-city", name: "Oklahoma City", stateSlug: "oklahoma", county: "Oklahoma", region: "okc", status: "PUBLISHED", officeAddress: null,
    zips: ["73102", "73103", "73104", "73105", "73106", "73107", "73108", "73109", "73110", "73111", "73112", "73114", "73115", "73116", "73118", "73119", "73120", "73122", "73127", "73132"],
    areas: ["Heritage Hills", "Mesta Park", "Crown Heights", "Nichols Hills border", "The Village border", "Quail Creek", "Westlake", "Capitol Hill", "Del City border", "Deer Creek area"],
    intro: "Oklahoma City sits in the center of Tornado Alley and sees damaging hail most years. The metro has been hit by some of the most destructive tornadoes on record, including the May 2013 storms. Housing ranges from early 20th-century homes in Heritage Hills and Mesta Park to postwar ranches and large newer subdivisions on the edges of the city.",
    housingNotes: "Historic neighborhoods have steep roofs, tile or slate in places, and masonry chimneys. Mid-century brick ranches cover much of the city. Newer homes on the north and west sides have builder-grade roofs that are often replaced after hail.",
    localIssues: [
      { title: "Hail and Class 4 roofs", body: "Hail is frequent, and Oklahoma insurers commonly offer discounts for [impact-resistant roofs](/roofing-services/impact-resistant-shingles/)." },
      { title: "Ice storms", body: "The October 2020 ice storm brought down trees across the city. Trimming limbs back from the roof reduces damage." },
      { title: "Storm-chasing contractors", body: "After big storms, out-of-state crews arrive. Oklahoma's roofing contractor registration lets homeowners verify who they hire." },
    ],
    popularServices: ["hail-damage-roof-repair", "impact-resistant-shingles", "storm-damage-roof-repair", "roof-insurance-claims", "emergency-roof-repair"],
    nearby: ["tulsa"],
    storm: "Hail, tornadoes and straight-line winds drive most roof claims. Many policies carry percentage-based wind and hail deductibles.",
    permits: "The City of Oklahoma City issues building permits for roofing work. Roofers must be registered with the Oklahoma Construction Industries Board. Suburbs such as Edmond and Norman have their own permit offices.",
    faqs: [
      { q: "How do I verify a roofer in Oklahoma City?", a: "Look up the contractor's roofing registration with the Oklahoma Construction Industries Board, and confirm insurance." },
      { q: "When is storm season in Oklahoma City?", a: "Spring is the most active season for hail and tornadoes, but severe storms can occur from March through fall." },
    ],
    updated: U,
  },
  {
    slug: "tulsa", name: "Tulsa", stateSlug: "oklahoma", county: "Tulsa", region: "tulsa", status: "PUBLISHED", officeAddress: null,
    zips: ["74103", "74104", "74106", "74107", "74110", "74112", "74115", "74119", "74120", "74126", "74127", "74128", "74129", "74132", "74134", "74136", "74137", "74145", "74146"],
    areas: ["Maple Ridge", "Brookside", "Cherry Street", "Midtown", "Swan Lake", "Florence Park", "South Tulsa", "Kendall-Whittier", "Owen Park", "Riverview"],
    intro: "Tulsa roofs face spring hail, tornadoes and ice storms, plus hot summers. The city has notable early 20th-century neighborhoods from its oil-boom years, such as Maple Ridge and Swan Lake, alongside mid-century Midtown homes and newer South Tulsa subdivisions.",
    housingNotes: "Maple Ridge and nearby historic neighborhoods have large homes with tile, slate and complex roofs. Midtown has many 1940s and 1950s brick homes. South Tulsa homes from the 1980s onward have architectural shingles frequently replaced after hail.",
    localIssues: [
      { title: "Hail", body: "Spring hail regularly damages roofs across Tulsa. Class 4 shingles are a common upgrade at replacement." },
      { title: "Tile and slate in historic homes", body: "Older Maple Ridge and Swan Lake homes may have clay tile or slate that needs roofers experienced with those materials." },
      { title: "Ice storms", body: "Ice storms such as the December 2007 event left widespread tree damage. Trees close to the roof are the biggest risk." },
    ],
    popularServices: ["hail-damage-roof-repair", "roof-replacement", "tile-roofing", "storm-damage-roof-repair", "roof-repair"],
    nearby: ["oklahoma-city"],
    storm: "Hail, tornadoes and ice storms are Tulsa's main roof risks, and severe spring storms can also bring damaging straight-line winds along the Arkansas River corridor. Many policies use percentage wind and hail deductibles.",
    permits: "The City of Tulsa issues building permits, and roofers must be registered with the Oklahoma Construction Industries Board. Historic preservation zoning applies in some neighborhoods.",
    faqs: [
      { q: "Can my Tulsa slate roof be repaired?", a: "Often yes. Slate is long-lived; broken slates and flashing can be repaired by a roofer who works with slate." },
      { q: "Do I need a permit to re-roof in Tulsa?", a: "Roofing work generally requires a permit from the City of Tulsa. The contractor should confirm and pull it." },
    ],
    updated: U,
  },
  {
    slug: "atlanta", name: "Atlanta", stateSlug: "georgia", county: "Fulton", region: "atlanta", status: "PUBLISHED", officeAddress: null,
    zips: ["30303", "30305", "30306", "30307", "30308", "30309", "30310", "30311", "30312", "30314", "30315", "30316", "30317", "30318", "30319", "30324", "30326", "30327", "30331", "30342"],
    areas: ["Inman Park", "Virginia-Highland", "Grant Park", "Kirkwood", "Midtown", "Buckhead", "West End", "Candler Park", "Morningside", "Cascade"],
    intro: "Atlanta is known as a city in a forest, and its tree canopy shapes roofing more than anything else: shade grows algae and moss, debris fills valleys, and storms drop limbs onto houses. Housing ranges from Victorian homes in Inman Park and bungalows in Virginia-Highland and Kirkwood to large homes in Buckhead.",
    housingNotes: "Intown neighborhoods have early 20th-century homes with steep roofs, dormers and porches tied into the main roof. Buckhead and northwest Atlanta homes often have complex roofs with many valleys. Infill homes add flat roof decks and metal accents.",
    localIssues: [
      { title: "Trees and debris", body: "Heavy canopy means leaves and limbs in valleys and gutters and damage when storms hit. Regular [roof maintenance](/roofing-services/roof-inspection/roof-maintenance/) and trimming prevent much of it." },
      { title: "Algae and moss", body: "Humid summers and shade grow black algae streaks and moss on north slopes. Soft washing removes them; pressure washing damages shingles." },
      { title: "Hail and severe storms", body: "Spring storms bring hail to Atlanta often enough that insurance-funded replacements are common." },
    ],
    popularServices: ["roof-maintenance", "storm-damage-roof-repair", "roof-leak-repair", "hail-damage-roof-repair", "roof-replacement"],
    nearby: [],
    storm: "Atlanta is inland, but severe thunderstorms, hail and tropical-storm remnants bring wind and falling trees. Tree damage is one of the most common causes of roof claims.",
    permits: "The City of Atlanta Office of Buildings issues permits. Historic districts such as Inman Park and Grant Park add review through the Urban Design Commission. Many metro addresses are in other cities or counties with their own rules.",
    faqs: [
      { q: "Why does my Atlanta roof have black streaks?", a: "Algae grows on shaded, humid roofs. Soft washing with a roof-safe cleaner removes it, and algae-resistant shingles slow its return." },
      { q: "Will insurance cover a tree that fell on my Atlanta roof?", a: "Damage from a tree knocked down by a covered storm is often covered. Photograph everything and call your insurer before cleanup." },
    ],
    updated: U,
  },
  {
    slug: "minneapolis", name: "Minneapolis", stateSlug: "minnesota", county: "Hennepin", region: "twin-cities", status: "PUBLISHED", officeAddress: null,
    zips: ["55401", "55403", "55404", "55405", "55406", "55407", "55408", "55409", "55410", "55411", "55412", "55413", "55414", "55416", "55417", "55418", "55419", "55422", "55423", "55430"],
    areas: ["Linden Hills", "Kingfield", "Longfellow", "Nokomis", "Northeast", "Uptown", "Powderhorn", "Camden", "Tangletown", "Seward"],
    intro: "Minneapolis roofs face long, cold winters with snow on the roof for weeks, which makes ice dams one of the city's defining roofing problems, plus summer hail that regularly hits the metro. Much of the city's housing is older: bungalows, 1.5-story homes and duplexes built before modern insulation.",
    housingNotes: "South Minneapolis is full of 1.5-story homes and bungalows with finished upper rooms tucked under the roof, where knee walls and sloped ceilings leak heat to the roof deck. Northeast has older worker cottages and duplexes. Many homes have masonry chimneys.",
    localIssues: [
      { title: "Ice dams on 1.5-story homes", body: "Heat loss through upper-story knee walls melts snow that refreezes at the eaves. [Ice dam removal](/roofing-services/roof-repair/ice-dam-removal/) with steam stops the immediate leak; air sealing and insulation stop the dams." },
      { title: "Summer hail", body: "Hailstorms cross the Twin Cities most summers, and many roofs are replaced through insurance claims." },
      { title: "Short re-roofing season", body: "Shingles need warm weather to seal, so most re-roofs happen from late spring to early fall." },
    ],
    popularServices: ["ice-dam-removal", "hail-damage-roof-repair", "roof-ventilation", "roof-replacement", "flashing-chimney-repair"],
    nearby: [],
    storm: "Hail and ice dams drive most claims. Minnesota law prohibits contractors from paying or rebating your insurance deductible.",
    permits: "The City of Minneapolis requires permits for re-roofing, and roofers must hold a Minnesota residential roofer license from the Department of Labor and Industry. Heritage preservation districts add design review.",
    faqs: [
      { q: "How do I stop ice dams on my Minneapolis bungalow?", a: "Seal air leaks into the attic and knee-wall spaces, add insulation, keep soffit vents clear, and install an eave ice barrier at the next re-roof." },
      { q: "Do I need a permit to re-roof in Minneapolis?", a: "Yes. The contractor pulls the city permit and must be licensed by the state." },
    ],
    updated: U,
  },
  {
    slug: "chicago", name: "Chicago", stateSlug: "illinois", county: "Cook", region: "chicago", status: "PUBLISHED", officeAddress: null,
    zips: ["60607", "60608", "60609", "60612", "60613", "60614", "60615", "60616", "60617", "60618", "60619", "60620", "60622", "60623", "60625", "60629", "60630", "60631", "60634", "60641"],
    areas: ["Bungalow Belt", "Lincoln Square", "Logan Square", "Portage Park", "Beverly", "Bridgeport", "Pilsen", "Rogers Park", "Ravenswood", "Hyde Park"],
    intro: "Chicago roofs deal with freeze-thaw winters, lake-effect wind and snow, summer storms and hail. The city's housing is dominated by brick bungalows, two-flats and three-flats, and greystones, many with flat roofs that need membranes rather than shingles.",
    housingNotes: "The Bungalow Belt has thousands of 1910s to 1940s brick bungalows with hip roofs and dormers. Two-flats and greystones usually have flat roofs behind parapets, draining to the rear. Many homes have masonry chimneys and multiple layers of past roofing.",
    localIssues: [
      { title: "Flat roofs on two-flats and greystones", body: "Parapet flashing, seams and rear drainage are the main leak sources. Modified bitumen, EPDM or TPO membranes are standard; see [flat roof repair](/roofing-services/flat-roof-repair/)." },
      { title: "Bungalow dormers and chimneys", body: "Dormer walls and brick chimneys need step flashing and counterflashing in good condition; freeze-thaw cracks mortar and loosens flashing." },
      { title: "Ice dams", body: "Bungalows with finished attics lose heat to the roof deck and form ice dams in snowy winters." },
    ],
    popularServices: ["flat-roof-repair", "flashing-chimney-repair", "ice-dam-removal", "roof-replacement", "roof-coatings"],
    nearby: [],
    storm: "Severe thunderstorms with wind and hail and winter snow are the main risks. Chicago's energy code includes reflective roof requirements for many low-slope roofs.",
    permits: "Roofers must hold an Illinois roofing license, and the City of Chicago Department of Buildings issues permits for roofing work. Landmark districts add review for visible changes.",
    faqs: [
      { q: "Does a Chicago flat roof need a reflective membrane?", a: "Many low-slope roofs in Chicago must meet the city's reflective roof requirements. Your roofer should confirm the requirement for your building." },
      { q: "Do Chicago roofers need a license?", a: "Yes. Roofing contractors must be licensed by the Illinois Department of Financial and Professional Regulation." },
    ],
    updated: U,
  },
  {
    slug: "philadelphia", name: "Philadelphia", stateSlug: "pennsylvania", county: "Philadelphia", region: "philadelphia", status: "PUBLISHED", officeAddress: null,
    zips: ["19103", "19104", "19106", "19107", "19111", "19114", "19115", "19116", "19118", "19119", "19120", "19121", "19122", "19123", "19124", "19125", "19128", "19130", "19131", "19134"],
    areas: ["South Philly", "Fishtown", "Kensington", "Northern Liberties", "Fairmount", "Manayunk", "Roxborough", "Mount Airy", "Chestnut Hill", "Northeast Philly"],
    intro: "Philadelphia is a city of rowhouses, and most of them have flat or low-slope roofs that share party walls with their neighbors. Freeze-thaw winters, heavy summer rain and the occasional tropical-storm remnant test those roofs, while Chestnut Hill, Mount Airy and parts of the Northeast have detached and twin homes with pitched roofs, slate and stone.",
    housingNotes: "Rowhouse roofs are typically flat with a slight pitch to the rear, coated or covered with modified bitumen, EPDM or TPO. Party-wall seams and rear gutters are common leak points. Northwest Philadelphia has stone homes with slate roofs and box gutters.",
    localIssues: [
      { title: "Rowhouse flat roofs", body: "Seams at party walls, rear scuppers and gutters, and aging coatings cause most leaks. [Flat roof repair](/roofing-services/flat-roof-repair/) and recoating are the most common jobs." },
      { title: "Roof coatings", body: "Reflective coatings are widely used on rowhouse roofs to extend membrane life and cool top floors. They work only on a sound, dry roof." },
      { title: "Slate and box gutters", body: "Older homes in Chestnut Hill, Mount Airy and Germantown often have slate roofs and built-in box gutters that need specialist repair." },
    ],
    popularServices: ["flat-roof-repair", "roof-coatings", "roof-leak-repair", "flashing-chimney-repair", "roof-replacement"],
    nearby: [],
    storm: "Heavy rain, freeze-thaw winters and tropical-storm remnants drive most roof problems. Ida in 2021 showed how much water the region can get in a single storm.",
    permits: "Philadelphia's Department of Licenses and Inspections issues permits and licenses contractors. Pennsylvania also requires home improvement contractor registration. The Philadelphia Historical Commission reviews work on designated properties.",
    faqs: [
      { q: "How long does a rowhouse flat roof last in Philadelphia?", a: "Membranes typically last about 15 to 25 years, longer with regular recoating and clear drainage." },
      { q: "Will repairing my roof affect my neighbor's?", a: "Rowhouse roofs meet at party walls, so the seam must be tied in properly. Good roofers coordinate the joint carefully." },
    ],
    updated: U,
  },
  {
    slug: "los-angeles", name: "Los Angeles", stateSlug: "california", county: "Los Angeles", region: "socal", status: "PUBLISHED", officeAddress: null,
    zips: ["90004", "90005", "90008", "90016", "90018", "90019", "90020", "90024", "90025", "90026", "90027", "90028", "90029", "90034", "90035", "90036", "90039", "90041", "90042", "90065"],
    areas: ["Silver Lake", "Echo Park", "Highland Park", "Los Feliz", "Mid-City", "Westwood", "Hancock Park", "Eagle Rock", "Leimert Park", "San Fernando Valley"],
    intro: "Los Angeles roofs face wildfire risk in the hillsides and canyons, as the January 2025 Palisades and Eaton fires showed, intense sun, and occasional winter atmospheric rivers that expose aging underlayment. Spanish-style homes with clay tile, Craftsman bungalows and postwar Valley ranches all have different roofing needs.",
    housingNotes: "1920s Spanish Revival homes in Los Feliz, Hancock Park and Mid-City often have clay tile and flat sections behind parapets. Highland Park and Eagle Rock have many Craftsman bungalows. San Fernando Valley ranches from the 1950s and 1960s have long, low roofs.",
    localIssues: [
      { title: "Wildfire zones", body: "Many hillside and canyon neighborhoods are in Very High Fire Hazard Severity Zones, where California's wildland-urban interface standards call for Class A roofs and ember-resistant features. See [wildfire-resistant roofing](/resources/wildfire-resistant-roofing/)." },
      { title: "Tile roof underlayment", body: "Clay and concrete tile can last for decades, but the underlayment beneath fails first. Lifting and relaying tiles over new underlayment is a common repair." },
      { title: "Cool roofs", body: "Los Angeles requires cool roofs for many new and replacement residential roofs. Ask your roofer which products meet the requirement." },
    ],
    popularServices: ["tile-roofing", "roof-leak-repair", "roof-replacement", "flat-roof-repair", "roof-inspection"],
    nearby: ["san-diego"],
    storm: "Wildfire is the dominant roof risk in hillside areas, with winter storms the main cause of leaks citywide. Wind events such as Santa Ana winds can loosen tiles and spread embers.",
    permits: "The Los Angeles Department of Building and Safety issues re-roof permits, and roofers need a California C-39 license or qualifying general license from the Contractors State License Board. Historic Preservation Overlay Zones add review.",
    faqs: [
      { q: "Do I need a cool roof in Los Angeles?", a: "Many residential re-roofs must meet LA's cool roof requirements. The contractor can confirm which products qualify for your home." },
      { q: "Why does my tile roof leak after rain?", a: "Usually the underlayment beneath the tiles has aged out, or tiles have cracked or slipped. A tile roofer can lift tiles and replace the underlayment." },
    ],
    updated: U,
  },
  {
    slug: "san-diego", name: "San Diego", stateSlug: "california", county: "San Diego", region: "socal", status: "PUBLISHED", officeAddress: null,
    zips: ["92101", "92102", "92103", "92104", "92105", "92106", "92107", "92108", "92109", "92110", "92111", "92115", "92116", "92117", "92119", "92120", "92122", "92124", "92126", "92128"],
    areas: ["North Park", "Mission Hills", "Kensington", "Point Loma", "Clairemont", "Pacific Beach", "Tierrasanta", "Scripps Ranch", "Rancho Bernardo", "University City"],
    intro: "San Diego's mild climate is easy on roofs most of the year, but wildfire is a serious risk on the city's canyon edges and eastern neighborhoods, as the Cedar and Witch Creek fires showed. Coastal neighborhoods add salt air and marine-layer moisture, and occasional winter storms reveal aging underlayment.",
    housingNotes: "North Park, Kensington and Mission Hills have Craftsman and Spanish Revival homes. Clairemont and much of the mid-city area were built as postwar tracts with low-slope roofs. Scripps Ranch, Tierrasanta and Rancho Bernardo sit next to canyons and open space.",
    localIssues: [
      { title: "Canyon-edge wildfire risk", body: "Homes bordering canyons and open space face ember exposure. Class A roofs, ember-resistant vents and clean gutters reduce risk." },
      { title: "Coastal salt air", body: "Point Loma, Ocean Beach and Pacific Beach see faster corrosion of flashing and fasteners. Corrosion-resistant metals extend roof life." },
      { title: "Low-slope postwar roofs", body: "Clairemont-era homes often have low-slope roofs where membrane and drainage condition matter more than shingle type." },
    ],
    popularServices: ["tile-roofing", "roof-inspection", "flat-roof-repair", "roof-replacement", "metal-roofing"],
    nearby: ["los-angeles"],
    storm: "Wildfire is the main roof hazard near canyons and the eastern edge of the city. Winter storms and Santa Ana winds are the other concerns.",
    permits: "The City of San Diego Development Services Department issues permits, and roofers need a California C-39 license or qualifying general license. Fire hazard zones add Class A roofing requirements.",
    faqs: [
      { q: "Is my San Diego home in a fire hazard zone?", a: "Many canyon-edge neighborhoods are. CAL FIRE's hazard maps and the city can confirm, and the zone affects which roofing assemblies are allowed." },
      { q: "How long do roofs last in San Diego?", a: "The mild climate helps, but sun and coastal moisture still age materials; tile underlayment and flat membranes usually need attention first." },
    ],
    updated: U,
  },
  {
    slug: "phoenix", name: "Phoenix", stateSlug: "arizona", county: "Maricopa", region: "phoenix", status: "PUBLISHED", officeAddress: null,
    zips: ["85003", "85004", "85006", "85007", "85008", "85012", "85013", "85014", "85015", "85016", "85018", "85019", "85020", "85021", "85022", "85023", "85024", "85027", "85028", "85032"],
    areas: ["Arcadia", "Willo", "Encanto-Palmcroft", "Coronado", "Biltmore", "Ahwatukee", "Paradise Valley Village", "Moon Valley", "Maryvale", "North Phoenix"],
    intro: "Phoenix roofs live under some of the most intense heat and sun in the country, then get tested by monsoon storms from July through September with high winds, dust and sudden downpours. Concrete tile, foam flat roofs and asphalt shingles are all common, and each fails in its own way in the desert.",
    housingNotes: "Historic districts such as Willo and Encanto-Palmcroft have 1920s to 1940s homes with flat roofs behind parapets. Arcadia and much of central Phoenix have mid-century ranches. Newer homes across North Phoenix and Ahwatukee mostly have concrete tile.",
    localIssues: [
      { title: "Tile underlayment", body: "Concrete tile lasts for decades, but desert heat breaks down the underlayment beneath it, which is the usual cause of tile roof leaks. See [tile roofing](/roofing-services/roof-replacement/tile-roofing/)." },
      { title: "Foam and flat roofs", body: "Spray polyurethane foam and membrane flat roofs need periodic recoating to stay watertight and reflective in the sun." },
      { title: "Monsoon storms", body: "Monsoon winds lift tiles and shingles and drive rain into weak flashing and clogged scuppers. Pre-season inspections catch problems." },
    ],
    popularServices: ["tile-roofing", "roof-coatings", "flat-roof-repair", "roof-leak-repair", "roof-inspection"],
    nearby: [],
    storm: "Monsoon wind and rain cause most sudden damage; heat and UV cause most long-term wear.",
    permits: "The City of Phoenix Planning and Development Department issues permits, and roofers must be licensed by the Arizona Registrar of Contractors. Historic districts add review.",
    faqs: [
      { q: "How often should a foam roof be recoated in Phoenix?", a: "Typically every several years, depending on the coating and its thickness. Your roofer can measure and recommend timing." },
      { q: "How do I verify a Phoenix roofer?", a: "Check the license on the Arizona Registrar of Contractors website." },
    ],
    updated: U,
  },
  {
    slug: "tampa", name: "Tampa", stateSlug: "florida", county: "Hillsborough", region: "tampa-bay", status: "PUBLISHED", officeAddress: null,
    zips: ["33602", "33603", "33604", "33605", "33606", "33607", "33609", "33610", "33611", "33612", "33613", "33614", "33615", "33616", "33617", "33618", "33619", "33624", "33626", "33629"],
    areas: ["Hyde Park", "Seminole Heights", "South Tampa", "Davis Islands", "Ybor City", "Westchase", "Carrollwood", "New Tampa", "Tampa Palms", "Palma Ceia"],
    intro: "Tampa roofs face hurricanes, heavy summer rain and intense sun. In 2024, Hurricane Helene's surge and Hurricane Milton's winds hit the Tampa Bay area within two weeks of each other, damaging roofs across the region. Housing ranges from 1920s bungalows in Seminole Heights and Hyde Park to newer homes in New Tampa and Westchase.",
    housingNotes: "Seminole Heights and Hyde Park have frame bungalows and older homes with steep roofs and porches. South Tampa and Davis Islands have Mediterranean-style homes with tile. Newer suburbs have shingle and tile roofs built to post-2002 Florida Building Code wind standards.",
    localIssues: [
      { title: "Hurricane wind", body: "Roof edges, ridge caps and older roofs built before the modern Florida code are most vulnerable. [Hurricane and wind damage repair](/roofing-services/storm-damage-roof-repair/wind-damage-roof-repair/) is the most common post-storm need." },
      { title: "Wind mitigation", body: "A wind mitigation inspection documents features such as roof deck attachment and roof-to-wall connections and can lower insurance premiums." },
      { title: "Summer rain", body: "Afternoon thunderstorms dump heavy rain daily in summer, testing flashing, valleys and flat sections." },
    ],
    popularServices: ["wind-damage-roof-repair", "emergency-roof-repair", "roof-insurance-claims", "tile-roofing", "roof-replacement"],
    nearby: ["miami"],
    storm: "Hurricanes and tropical storms are Tampa's dominant roof risk. Florida policies often carry a separate hurricane deductible, usually a percentage of dwelling coverage.",
    permits: "The City of Tampa issues permits inside city limits, and unincorporated areas go through Hillsborough County. Roofers must hold a Florida roofing contractor license, and work follows the Florida Building Code.",
    faqs: [
      { q: "What is a wind mitigation inspection in Tampa?", a: "An inspection documenting your roof's wind-resistant features on a standard form that insurers use to apply premium discounts." },
      { q: "How do I verify a Tampa roofer?", a: "Look up the Florida roofing license on the DBPR website before signing." },
    ],
    updated: U,
  },
  {
    slug: "miami", name: "Miami", stateSlug: "florida", county: "Miami-Dade", region: "south-florida", status: "PUBLISHED", officeAddress: null,
    zips: ["33125", "33126", "33127", "33128", "33129", "33130", "33131", "33133", "33134", "33135", "33137", "33138", "33142", "33143", "33144", "33145", "33147", "33150", "33155", "33156"],
    areas: ["Coconut Grove", "Little Havana", "Shenandoah", "Brickell", "Upper East Side", "Little River", "Flagami", "Allapattah", "Kendall area", "Miami Shores border"],
    intro: "Miami is in Florida's High-Velocity Hurricane Zone, which has the strictest roofing requirements in the country. The code reforms that followed Hurricane Andrew in 1992 still shape how roofs are built here, and tile, flat roofs and metal are all common on Miami homes.",
    housingNotes: "Coconut Grove and Shenandoah have older homes with tile and flat sections. Little Havana and Allapattah have many 1920s to 1950s homes with flat or low-slope roofs. Newer homes and townhomes have tile or metal roofs built to current wind standards.",
    localIssues: [
      { title: "HVHZ product approvals", body: "Roofing products in Miami-Dade must carry specific approvals for the High-Velocity Hurricane Zone, and installation follows the HVHZ provisions of the Florida Building Code." },
      { title: "Flat and low-slope roofs", body: "Many older homes have flat roofs that need membranes, proper drainage and careful flashing at parapets. See [flat roof repair](/roofing-services/flat-roof-repair/)." },
      { title: "Tile and salt air", body: "Tile underlayment wears out first, and salt air corrodes fasteners and flashing near the bay and ocean." },
    ],
    popularServices: ["tile-roofing", "flat-roof-repair", "wind-damage-roof-repair", "roof-insurance-claims", "metal-roofing"],
    nearby: ["tampa"],
    storm: "Hurricanes are Miami's dominant roof risk. Insurers weigh roof age and wind mitigation features heavily, and policies usually carry a percentage hurricane deductible.",
    permits: "The City of Miami Building Department issues permits inside city limits; other municipalities and unincorporated areas go through their own offices or Miami-Dade County. Roofers must hold a Florida roofing contractor license.",
    faqs: [
      { q: "What is the High-Velocity Hurricane Zone?", a: "The part of the Florida Building Code that applies in Miami-Dade and Broward counties, with stricter product approval and installation requirements for wind." },
      { q: "Why do insurers ask about my Miami roof's age?", a: "Roof age and condition strongly affect hurricane risk. A recent roof and a wind mitigation inspection can improve coverage options and premiums." },
    ],
    updated: U,
  },
];
