import type { Service } from "./types";

const U = "2026-10-05";

// Subservices and specialty services. Merged in services.ts. Parents are set in serviceTree.ts.
export const servicesMore: Service[] = [
  {
    slug: "ice-dam-removal",
    name: "Ice Dam Removal & Prevention",
    shortName: "Ice dams",
    category: "repair",
    status: "PUBLISHED",
    seoTitle: "Ice Dam Removal & Prevention for Your Roof",
    metaDescription:
      "What causes ice dams, how they're safely removed with steam, the leaks they cause, and the insulation, ventilation and ice-barrier fixes that prevent them.",
    h1: "Ice dam removal and prevention",
    answer:
      "An ice dam forms when heat escaping into the attic melts snow higher on the roof and the water refreezes at the colder eaves. The ridge of ice backs water up under the shingles. Professionals remove dams with low-pressure steam, and prevention comes from air sealing, insulation, ventilation and an ice barrier membrane.",
    intro: [
      "Ice dams are a winter problem across the snow belt: New England, New York, the Upper Midwest, the Great Lakes states, and mountain areas of the West. They're most common on homes with warm attics, complex roof lines, and older houses built before ice barrier membranes were standard.",
      "Model building codes require an ice barrier extending from the eave edge to at least 24 inches inside the exterior wall in areas where ice dams have a history of forming. That membrane limits leaks when a dam forms, but stopping attic heat loss is what stops dams.",
    ],
    signs: [
      "Thick ridges of ice along the eaves",
      "Large icicles hanging from gutters",
      "Water stains on ceilings or exterior walls during thaws",
      "Frost or wet insulation in the attic",
      "Snow melting on the upper roof while the eaves stay frozen",
    ],
    process: [
      { title: "Remove", body: "A crew uses low-pressure steam to cut channels through the dam so water can drain, without damaging shingles." },
      { title: "Trace the heat loss", body: "Attic bypasses around lights, chimneys, plumbing stacks and hatches are identified." },
      { title: "Fix the cause", body: "Air sealing, added insulation and balanced ventilation keep the roof deck cold." },
      { title: "Protect the eaves", body: "At the next re-roof, an ice barrier membrane is installed along the eaves and valleys." },
    ],
    costFactors: [
      "Length of eaves and thickness of the ice",
      "Roof height and access in snow",
      "Interior water damage",
      "Attic air sealing and insulation work",
      "Adding ice barrier during a re-roof",
    ],
    diy: {
      safe: ["Clear snow from the lower few feet of the roof with a roof rake from the ground", "Keep gutters and downspouts clear before winter", "Catch interior drips and move belongings"],
      stop: ["Chipping ice with hammers, chisels or axes", "Climbing onto an icy roof", "Using salt products that damage shingles, metal and plants"],
    },
    faqs: [
      { q: "Do heat cables prevent ice dams?", a: "They can keep drainage paths open in trouble spots, but they don't fix the attic heat loss that causes ice dams. Air sealing and insulation are the lasting fix." },
      { q: "Is ice dam damage covered by insurance?", a: "Interior water damage from ice dams is often covered under standard homeowners policies, while removal and prevention usually aren't. Check your policy." },
    ],
    related: ["roof-leak-repair", "roof-ventilation", "roof-replacement", "fascia-soffit-repair"],
    isEmergencyCapable: true,
    glance: [
      { term: "Cause", detail: "Attic heat melting snow that refreezes at the eaves" },
      { term: "Safe removal", detail: "Low-pressure steam" },
      { term: "Code protection", detail: "Ice barrier to 24 inches inside the exterior wall" },
      { term: "Common in", detail: "Northeast, Great Lakes, Upper Midwest and mountain West" },
    ],
    updated: U,
  },
  {
    slug: "asphalt-shingle-roofing",
    name: "Asphalt Shingle Roofing",
    shortName: "Shingle roofing",
    category: "replacement",
    status: "PUBLISHED",
    seoTitle: "Asphalt Shingle Roofing: Types, Ratings & Warranties",
    metaDescription:
      "Architectural vs. three-tab vs. designer shingles, wind and algae ratings, colors for hot and cold climates, and how shingle warranties really work.",
    h1: "Asphalt shingle roofing",
    answer:
      "Architectural (dimensional) asphalt shingles are the most common roof on American homes because they balance cost, appearance and wind performance. Choose by your climate: a high wind rating with enhanced nailing on the coasts and Plains, algae-resistant granules in humid regions, and a color that suits your attic and any HOA rules.",
    intro: [
      "Three-tab shingles have largely given way to architectural shingles, which are thicker, rated for higher wind and longer-lasting. Premium lines add heavier mats, impact resistance or reflective granules.",
      "Humid regions, especially the Southeast and Gulf Coast, see black streaks from Gloeocapsa magma algae, so copper-infused algae-resistant granules are worth asking for. In hot climates lighter or reflective (cool roof) shingles can lower attic temperatures; California's energy code includes cool roof requirements in some situations.",
    ],
    signs: [
      "You're replacing a roof and comparing materials",
      "Current shingles are three-tab and near the end of their life",
      "Algae streaks keep returning",
      "You want better wind ratings on an exposed lot",
      "An HOA requires a specific color family",
    ],
    process: [
      { title: "Choose a line", body: "Compare standard architectural, designer and impact-resistant options from the same manufacturer." },
      { title: "System components", body: "Matching starter strips, hip and ridge caps, and underlayment can qualify for an extended manufacturer warranty." },
      { title: "Install", body: "Shingles are fastened with the manufacturer's high-wind nailing pattern and correct exposure." },
      { title: "Register", body: "The warranty is registered in your name, with installer certification noted if it applies." },
    ],
    costFactors: ["Shingle line and weight", "System warranty requirements", "Hip and ridge length", "Algae-resistant or reflective granules", "Local supply after storms"],
    faqs: [
      { q: "What shingle color is best for a hot climate?", a: "Lighter and reflective colors absorb less heat and can lower attic temperatures somewhat. Ventilation and insulation matter more, and your HOA may limit choices." },
      { q: "Are architectural shingles worth it over three-tab?", a: "Yes for most homes. They resist wind better, last longer and are now the standard product." },
      { q: "What do shingle warranties cover?", a: "Manufacturer warranties cover material defects; workmanship is covered separately by the contractor. Enhanced system warranties require specific components and certified installers." },
    ],
    related: ["impact-resistant-shingles", "metal-roofing", "roof-ventilation", "roof-maintenance"],
    isEmergencyCapable: false,
    glance: [
      { term: "Most common type", detail: "Architectural (dimensional) shingles" },
      { term: "Humid climates", detail: "Algae-resistant granules" },
      { term: "Windy areas", detail: "High-wind rating with enhanced nailing" },
      { term: "Warranty", detail: "Material plus a separate workmanship warranty" },
    ],
    updated: U,
  },
  {
    slug: "impact-resistant-shingles",
    name: "Impact-Resistant (Class 4) Shingles",
    shortName: "Class 4 shingles",
    category: "replacement",
    status: "PUBLISHED",
    seoTitle: "Class 4 Impact-Resistant Shingles: Worth It?",
    metaDescription:
      "How the UL 2218 Class 4 rating works, which states see the most hail, insurance discounts for impact-resistant roofs, and when the upgrade pays off.",
    h1: "Class 4 impact-resistant shingles",
    answer:
      "Class 4 shingles passed the UL 2218 test, in which a 2-inch steel ball is dropped onto the shingle without cracking it. They resist hail better than standard shingles, and insurers in many hail-prone states offer premium discounts for them, which can offset part of the added cost.",
    intro: [
      "Impact-resistant shingles use rubberized (SBS-modified) asphalt or a reinforced mat that flexes instead of fracturing. They look like standard architectural shingles, so they work under most HOA rules.",
      "They make the most sense in hail country, from Texas and Oklahoma north through Kansas, Nebraska, Colorado, the Dakotas and Minnesota, and for homeowners replacing a roof after a hail claim. Some states require insurers to offer a discount; ask yours for the exact amount before deciding.",
    ],
    signs: ["You're replacing a roof after hail", "Your area has had repeated hail claims", "Your insurer offers an impact-resistant discount", "You plan to stay in the home for many years", "You want a stronger wind rating too"],
    process: [
      { title: "Check the discount", body: "Ask your insurer what documentation it needs, usually the product name and a certificate or invoice." },
      { title: "Choose the product", body: "Compare Class 4 lines for wind rating, colors and warranty." },
      { title: "Install", body: "The roof is installed to the manufacturer's specification so the rating and warranty hold." },
      { title: "Submit paperwork", body: "You send the insurer the installation documentation to apply the discount." },
    ],
    costFactors: ["Product line (SBS-modified vs. reinforced mat)", "Roof size and complexity", "Upgrade cost over the shingle your claim pays for", "Annual insurance discount over the roof's life", "Matching hip and ridge caps"],
    faqs: [
      { q: "Are Class 4 shingles hail-proof?", a: "No. They resist impact much better than standard shingles, but very large hail can still damage them." },
      { q: "How much is the insurance discount?", a: "It varies by state, insurer and policy. Ask your agent for the exact figure before choosing." },
      { q: "Can I upgrade to Class 4 during an insurance claim?", a: "Usually yes, by paying the difference between the approved shingle and the Class 4 product." },
    ],
    related: ["hail-damage-roof-repair", "asphalt-shingle-roofing", "metal-roofing", "roof-insurance-claims"],
    isEmergencyCapable: false,
    glance: [
      { term: "Rating", detail: "UL 2218 Class 4" },
      { term: "Test", detail: "2-inch steel ball dropped without cracking" },
      { term: "Best fit", detail: "Hail-prone Plains, Front Range and Upper Midwest" },
      { term: "Looks like", detail: "Standard architectural shingles" },
    ],
    updated: U,
  },
  {
    slug: "metal-roofing",
    name: "Metal Roofing",
    shortName: "Metal roofing",
    category: "replacement",
    status: "PUBLISHED",
    seoTitle: "Metal Roofing: Standing Seam vs. Exposed Fastener",
    metaDescription:
      "Standing seam and exposed-fastener metal roofs: lifespan, wind and snow performance, fire resistance, coastal corrosion and cost factors.",
    h1: "Metal roofing",
    answer:
      "A standing seam metal roof uses concealed clips and raised seams, resists high wind, sheds snow, reflects heat and can last 40 years or more. Exposed-fastener panels cost less but need screws re-checked over time. Near salt water, ask for aluminum or a coastal-rated finish and stainless fasteners.",
    intro: [
      "Metal roofing suits very different climates: it sheds heavy snow in the mountains and Northeast, resists wildfire embers in the West as a noncombustible covering, handles hurricane winds when properly fastened, and reflects summer heat in the South.",
      "Where snow slides, plan for snow guards above entries, decks and walkways. On the coast, salt spray corrodes cut edges and fasteners, so material and finish selection matters more than color.",
    ],
    signs: ["You want a roof that outlasts the mortgage", "Your home faces heavy snow, high wind or wildfire risk", "You're adding a porch or patio cover", "You want lower attic temperatures", "Your HOA allows metal roofing"],
    process: [
      { title: "Design", body: "Panel profile, gauge, finish and color are chosen, with HOA or historic approval if needed." },
      { title: "Prepare", body: "The deck is repaired and a high-temperature underlayment is installed, plus ice barrier where code requires it." },
      { title: "Install", body: "Panels, trims and flashings are set with clips or fasteners spaced to the wind rating." },
      { title: "Detail", body: "Ridge vents, pipe flashings, snow guards and transitions are sealed and secured." },
    ],
    costFactors: ["Standing seam vs. exposed-fastener panels", "Steel gauge or aluminum", "Finish system (PVDF vs. polyester)", "Roof complexity and penetrations", "Snow guards and coastal-rated materials"],
    faqs: [
      { q: "Is a metal roof louder in the rain?", a: "Over solid decking and underlayment with an insulated attic, it's usually not much louder than shingles." },
      { q: "Does a metal roof attract lightning?", a: "No. It doesn't increase the chance of a strike, and it isn't combustible if one happens." },
      { q: "Is metal good in snow country?", a: "Yes. Snow slides off more readily, which reduces load and ice-dam risk, but snow guards are needed where sliding snow could hurt people or gutters." },
    ],
    related: ["asphalt-shingle-roofing", "tile-roofing", "impact-resistant-shingles", "roof-coatings"],
    isEmergencyCapable: false,
    glance: [
      { term: "Lifespan", detail: "40 years or more for standing seam" },
      { term: "Strengths", detail: "Wind, snow shedding, fire resistance, heat reflection" },
      { term: "Coastal", detail: "Aluminum or coastal-rated finishes and stainless fasteners" },
      { term: "Snow areas", detail: "Snow guards over entries and walkways" },
    ],
    updated: U,
  },
  {
    slug: "tile-roofing",
    name: "Tile Roofing (Clay & Concrete)",
    shortName: "Tile roofing",
    category: "replacement",
    status: "PUBLISHED",
    seoTitle: "Tile Roof Repair & Underlayment Replacement",
    metaDescription:
      "Clay and concrete tile roofs: cracked tile repair, underlayment replacement, wind attachment, and what tile roofs in Florida, Arizona and California need.",
    h1: "Tile roof repair and replacement",
    answer:
      "Clay and concrete tiles often outlast the underlayment beneath them. Most tile roof leaks come from aged underlayment, cracked or slipped tiles, and flashing, so a common job is lifting the tiles, replacing the underlayment and battens, and relaying the same tiles with new ones where needed.",
    intro: [
      "Tile roofs are common in Florida, Arizona, Southern California, Nevada and parts of Texas and New Mexico, where they suit hot, sunny climates and Spanish and Mediterranean styles. Concrete tile is heavier and less expensive than clay.",
      "In hurricane regions, tile attachment matters: Florida's building code specifies how tiles are fastened or adhered to resist wind. Walking on tile cracks it, so inspections and repairs should be left to roofers who work with tile regularly.",
    ],
    signs: ["Cracked, slipped or missing tiles", "Leaks despite tiles that look intact", "Underlayment 20 or more years old", "Debris and dams in valleys", "Mortar breaking up at ridges and hips"],
    process: [
      { title: "Inspect", body: "The roofer checks tiles, ridges, valleys and, by lifting sample tiles, the underlayment." },
      { title: "Repair", body: "Cracked tiles are replaced and slipped tiles reset; ridge and hip mortar or fasteners are redone." },
      { title: "Underlayment replacement", body: "Tiles are removed and stacked, new underlayment and battens installed, and tiles relaid with replacements as needed." },
      { title: "Attach to code", body: "Tiles are fastened or adhered to the wind requirements for your area." },
    ],
    costFactors: ["Clay vs. concrete tile", "Availability of matching replacement tiles", "Underlayment type", "Roof size and pitch", "Wind attachment requirements"],
    faqs: [
      { q: "How long does a tile roof last?", a: "The tiles themselves can last 50 years or more, but underlayment often needs replacing after about 20 to 30 years, depending on type and climate." },
      { q: "Can I walk on my tile roof?", a: "It's best not to. Tiles crack under foot traffic; a tile roofer knows where to step and how to spread load." },
    ],
    related: ["roof-leak-repair", "metal-roofing", "roof-inspection", "wind-damage-roof-repair"],
    isEmergencyCapable: false,
    glance: [
      { term: "Fails first", detail: "Underlayment beneath the tiles" },
      { term: "Common in", detail: "Florida, Arizona, Southern California and Nevada" },
      { term: "Tile life", detail: "50 years or more" },
      { term: "Coastal rule", detail: "Wind-rated attachment" },
    ],
    updated: U,
  },
  {
    slug: "flat-roof-repair",
    name: "Flat Roof Repair & Replacement",
    shortName: "Flat roofs",
    category: "flat",
    status: "PUBLISHED",
    seoTitle: "Flat Roof Repair & Replacement (TPO, EPDM, Mod Bit)",
    metaDescription:
      "Flat and low-slope roof repair and replacement: TPO, EPDM, modified bitumen, ponding water, porches, additions and rowhouse roofs.",
    h1: "Flat and low-slope roof repair",
    answer:
      "Flat and low-slope roofs need membranes, not shingles: modified bitumen, EPDM rubber, TPO or similar systems. Most failures come from ponding water, open seams and flashing at walls. A roofer repairs seams and flashing, or replaces the membrane with better drainage.",
    intro: [
      "Flat sections show up everywhere: rowhouses in Philadelphia, Baltimore and Washington, triple-deckers in New England, mid-century modern homes, porches, garage additions and patio covers. Shingles can't be used below a 2:12 pitch, so these areas need a membrane.",
      "Water that sits for more than 48 hours after rain, called ponding, breaks down membranes and finds every weak seam. In cold climates, freezing ponded water adds stress. Fixing the slope or adding a scupper often matters more than the patch.",
    ],
    signs: ["Water standing two days after rain", "Blisters, cracks or alligatoring in the surface", "Open seams or lifted edges", "Leaks where a flat section meets a wall or the main roof", "Soft spots underfoot"],
    process: [
      { title: "Inspect", body: "Seams, flashing, drains and scuppers are checked, and wet insulation is located if there is any." },
      { title: "Fix drainage", body: "Tapered insulation, crickets or added scuppers move water off the roof." },
      { title: "Repair or replace", body: "Seams and flashing are repaired, or the membrane is replaced with modified bitumen, EPDM or TPO." },
      { title: "Detail transitions", body: "Wall and roof-to-roof transitions get counterflashing and termination bars." },
    ],
    costFactors: ["Membrane type and thickness", "Wet insulation or decking to replace", "Drainage corrections", "Access on rowhouses and rooftop decks", "Number of penetrations and walls"],
    diy: {
      safe: ["Keep drains and scuppers clear of leaves", "Photograph ponding after storms", "Note where leaks show inside"],
      stop: ["Patching with roofing tar over a wet membrane", "Walking on soft or blistered areas", "Using a torch near wood or siding"],
    },
    faqs: [
      { q: "How long does a flat roof last?", a: "Modified bitumen, EPDM and TPO typically last about 15 to 30 years with good drainage and maintenance." },
      { q: "Is ponding water a problem?", a: "Water that clears within 48 hours is usually acceptable. Longer ponding shortens membrane life and should be corrected." },
      { q: "Which membrane is best?", a: "It depends on the roof and climate. TPO reflects heat and suits sunny areas, EPDM is durable and flexible in cold, and modified bitumen is common on residential flat roofs." },
    ],
    related: ["roof-coatings", "roof-leak-repair", "flashing-chimney-repair", "roof-inspection"],
    isEmergencyCapable: true,
    glance: [
      { term: "Systems", detail: "Modified bitumen, EPDM and TPO" },
      { term: "Below 2:12", detail: "A membrane is required, not shingles" },
      { term: "Watch for", detail: "Ponding longer than 48 hours" },
      { term: "Common on", detail: "Rowhouses, porches, additions and patio covers" },
    ],
    updated: U,
  },
  {
    slug: "roof-coatings",
    name: "Roof Coatings",
    shortName: "Roof coatings",
    category: "flat",
    status: "PUBLISHED",
    seoTitle: "Silicone & Reflective Roof Coatings Explained",
    metaDescription:
      "Silicone and acrylic coatings for flat and metal roofs: when a coating extends roof life, when it doesn't, prep steps and climate considerations.",
    h1: "Silicone and reflective roof coatings",
    answer:
      "A roof coating is a fluid-applied membrane, usually silicone or acrylic, rolled or sprayed over a sound flat or metal roof. It seals small cracks and fasteners and reflects sunlight. It doesn't fix a roof with wet insulation or failed decking; that has to be repaired first.",
    intro: [
      "Coatings make sense on aging but sound flat roofs and exposed-fastener metal roofs, where they can add years of life for much less than replacement. White reflective coatings cut surface temperatures in sunny climates from the Southwest to the Southeast.",
      "Silicone tolerates ponding water better than acrylic. Preparation is most of the job: cleaning, repairing seams, and confirming the roof is dry underneath. Application needs a dry forecast and temperatures within the product's range, which limits the season in colder states.",
    ],
    signs: ["Aging flat roof without major leaks", "Rusting fasteners on a metal roof", "Hot rooms beneath a dark flat roof", "Minor surface cracking", "You want to delay a full replacement"],
    process: [
      { title: "Moisture check", body: "The roof is inspected, and suspected wet areas are cored or scanned." },
      { title: "Prep", body: "Wet sections are replaced, seams and fasteners reinforced, and the surface cleaned." },
      { title: "Apply", body: "Primer if required, then the coating at the specified thickness." },
      { title: "Document", body: "You receive the product and thickness details for any manufacturer warranty." },
    ],
    costFactors: ["Coating type (silicone vs. acrylic)", "Required thickness and warranty length", "Repairs needed before coating", "Roof size and access", "Number of penetrations"],
    faqs: [
      { q: "Can a coating go over shingles?", a: "Coatings are generally meant for flat and metal roofs, not asphalt shingles. Shingle roofs need repair or replacement instead." },
      { q: "How long does a roof coating last?", a: "Typically about 10 to 15 years depending on thickness and product, and many can be recoated later." },
    ],
    related: ["flat-roof-repair", "metal-roofing", "roof-maintenance", "roof-inspection"],
    isEmergencyCapable: false,
    glance: [
      { term: "Works on", detail: "Sound flat and metal roofs" },
      { term: "Ponding areas", detail: "Silicone" },
      { term: "Not for", detail: "Wet roofs or asphalt shingles" },
      { term: "Key step", detail: "Moisture check and surface prep" },
    ],
    updated: U,
  },
  {
    slug: "roof-inspection",
    name: "Roof Inspection",
    shortName: "Roof inspection",
    category: "inspection",
    status: "PUBLISHED",
    seoTitle: "Roof Inspection: What's Checked and When You Need One",
    metaDescription:
      "Roof inspections for homeowners, buyers, sellers and insurers: storm checks, insurance condition reports, attic checks and photo documentation.",
    h1: "Roof inspection",
    answer:
      "A roof inspection checks every slope, the flashing, vents, gutters and the attic underside, then reports condition, damage and remaining life with photos. Homeowners order them after storms, before insurance renewals, before winter or hurricane season, and when buying or selling a house.",
    intro: [
      "More insurers now ask for roof age or condition before renewing a policy, especially in hail and hurricane states and for roofs over 10 to 15 years old. An inspection with photos gives you an accurate record instead of a guess.",
      "If you're buying a home, a general home inspector's roof notes are a starting point. A roofer can tell you whether the issues are repairs or a replacement, which matters in negotiations.",
    ],
    signs: ["A storm passed through recently", "Your insurer asked about the roof's age or condition", "You're buying or selling a home", "The roof is 10 or more years old", "You've noticed granules, stains or missing shingles"],
    process: [
      { title: "Exterior", body: "Every slope, valley, flashing detail, vent and gutter is checked and photographed." },
      { title: "Attic", body: "Decking, ventilation, insulation and signs of past leaks or ice dams are reviewed from inside." },
      { title: "Report", body: "You get photos, condition notes and an estimate of remaining life." },
      { title: "Recommendations", body: "Repairs are prioritized, with an honest call on whether replacement is near." },
    ],
    costFactors: ["Free storm inspections vs. paid written reports", "Roof size and height", "Drone or ladder access", "Detailed reports for real estate or insurance", "Attic access"],
    faqs: [
      { q: "How often should I get my roof inspected?", a: "Once a year and after any major storm is a good rule, ideally before your region's hardest season: hurricane season on the coasts, winter in snow country, or spring hail season on the Plains." },
      { q: "Are free roof inspections legitimate?", a: "Many roofers inspect for free after storms. Treat the findings as a starting point and get a second opinion before signing a contract for a full replacement." },
    ],
    related: ["roof-maintenance", "storm-damage-roof-repair", "roof-insurance-claims", "roof-repair"],
    isEmergencyCapable: false,
    glance: [
      { term: "Covers", detail: "Slopes, flashing, vents, gutters and attic" },
      { term: "When", detail: "Yearly, after storms, and at sale or renewal" },
      { term: "You receive", detail: "Photos, condition notes and remaining life" },
      { term: "Useful for", detail: "Insurance renewals and home sales" },
    ],
    updated: U,
  },
  {
    slug: "roof-maintenance",
    name: "Roof Maintenance & Cleaning",
    shortName: "Roof maintenance",
    category: "inspection",
    status: "PUBLISHED",
    seoTitle: "Roof Maintenance & Cleaning: A Seasonal Checklist",
    metaDescription:
      "Roof maintenance by season: debris and needle removal, algae and moss cleaning, sealant touch-ups, pipe boots, and pre-winter and pre-storm checks.",
    h1: "Roof maintenance and cleaning",
    answer:
      "Roof maintenance means clearing leaves and needles from valleys and gutters, replacing aging pipe boots, resealing exposed fasteners and flashing, and soft-washing algae or removing moss. A yearly visit before your region's hardest season catches small problems before storms or snow do.",
    intro: [
      "What maintenance matters most depends on climate. Moss is the big issue in the Pacific Northwest's damp winters, algae streaks in the humid Southeast, pine needles and debris in wooded areas, and gutter and ice-dam prep before winter across the North.",
      "Black streaks are algae, not dirt. Low-pressure soft washing with a roof-safe cleaner removes them; pressure washing strips granules and shortens the roof's life.",
    ],
    signs: ["Leaves or needles piled in valleys", "Black streaks or moss on shaded slopes", "Branches touching or hanging over the roof", "Gutters overflowing in heavy rain", "Cracked boots or exposed nail heads"],
    process: [
      { title: "Clear", body: "Valleys, gutters and the roof surface are cleared of debris." },
      { title: "Seal", body: "Exposed fasteners, flashing edges and boots are inspected and resealed or replaced." },
      { title: "Clean", body: "Algae is soft-washed and moss removed with roof-safe methods where requested." },
      { title: "Report", body: "You get photos of anything that needs repair before the next season." },
    ],
    costFactors: ["Roof size and pitch", "Amount of debris and tree cover", "Soft washing or moss treatment", "Boot and sealant replacements", "Gutter cleaning"],
    faqs: [
      { q: "Should I pressure wash my roof?", a: "No. High pressure strips granules and can void shingle warranties. Use low-pressure soft washing instead." },
      { q: "Is moss bad for my roof?", a: "Yes. Moss holds moisture against shingles and can lift them, so it should be removed and its regrowth slowed with zinc or copper strips." },
    ],
    related: ["roof-inspection", "roof-repair", "roof-ventilation", "asphalt-shingle-roofing"],
    isEmergencyCapable: false,
    glance: [
      { term: "Best timing", detail: "Before your region's storm or winter season" },
      { term: "Algae", detail: "Soft wash, never pressure wash" },
      { term: "Moss", detail: "Common in the Pacific Northwest and shaded roofs" },
      { term: "Replace", detail: "Pipe boots before they crack" },
    ],
    updated: U,
  },
  {
    slug: "roof-ventilation",
    name: "Attic & Roof Ventilation",
    shortName: "Roof ventilation",
    category: "components",
    status: "PUBLISHED",
    seoTitle: "Attic & Roof Ventilation: How It Works",
    metaDescription:
      "Balanced attic ventilation explained: soffit intake, ridge vents, why mixing vent types backfires, and how ventilation affects heat, moisture and ice dams.",
    h1: "Attic and roof ventilation",
    answer:
      "Good attic ventilation pulls outside air in at the soffits and exhausts it at the ridge, which keeps the roof deck cooler in summer and drier and colder in winter. Poor ventilation bakes shingles in hot climates, feeds condensation and ice dams in cold ones, and can void parts of shingle warranties.",
    intro: [
      "In the South and Southwest, attics above dark shingles can run far hotter than the outdoor air on summer afternoons, aging shingles from below. In the North, warm, moist air leaking into the attic condenses on cold decking and melts snow into ice dams.",
      "Mixing exhaust types, such as turbines with a ridge vent or a powered fan with gable vents, can short-circuit the airflow. The fix is usually one exhaust type with enough soffit intake, plus air sealing between the house and the attic.",
    ],
    signs: ["Upstairs rooms much hotter than downstairs", "Shingles blistering or aging early", "Painted-over or blocked soffit vents", "Frost, mildew or damp insulation in the attic", "A mix of turbines, gable vents and ridge vents"],
    process: [
      { title: "Measure", body: "Attic area, intake and exhaust openings are compared with code and the shingle manufacturer's ratio." },
      { title: "Balance", body: "Soffit vents are opened or added, and one exhaust type is chosen." },
      { title: "Install", body: "Ridge vent, low-profile vents or other exhaust is installed with proper flashing." },
      { title: "Check baffles", body: "Insulation baffles keep soffit intake clear of blown insulation." },
    ],
    costFactors: ["Ridge length and roof design", "Soffit material and condition", "Baffles, air sealing and insulation work", "Removing old vents and patching", "Doing it during a re-roof (lower cost)"],
    faqs: [
      { q: "Are turbine vents good?", a: "They can work, but they shouldn't be mixed with a ridge vent. Many re-roofs replace turbines with a continuous ridge vent and better soffit intake." },
      { q: "Does ventilation prevent ice dams?", a: "It helps keep the roof deck cold, but air sealing and insulation do most of the work. Ventilation removes the heat and moisture that still get through." },
    ],
    related: ["ice-dam-removal", "roof-replacement", "fascia-soffit-repair", "roof-maintenance"],
    isEmergencyCapable: false,
    glance: [
      { term: "Principle", detail: "Intake at the soffits, exhaust at the ridge" },
      { term: "Hot climates", detail: "Reduces attic heat that ages shingles" },
      { term: "Cold climates", detail: "Limits condensation and ice dams" },
      { term: "Avoid", detail: "Mixing exhaust types" },
    ],
    updated: U,
  },
  {
    slug: "flashing-chimney-repair",
    name: "Flashing & Chimney Leak Repair",
    shortName: "Flashing repair",
    category: "components",
    status: "PUBLISHED",
    seoTitle: "Roof Flashing & Chimney Leak Repair",
    metaDescription:
      "Flashing repair at chimneys, walls, dormers, valleys and pipes: why flashing causes most roof leaks and how step flashing and counterflashing fix them.",
    h1: "Flashing and chimney leak repair",
    answer:
      "Flashing is the metal or membrane that seals the joints where a roof meets a chimney, wall, dormer or pipe. When it rusts, pulls loose or was only caulked, water gets in. Proper repair replaces it with step flashing and counterflashing, not more sealant.",
    intro: [
      "Every roof-to-wall joint depends on step flashing and a kick-out at the bottom. Missing kick-out flashing sends water behind siding and is a common hidden rot problem on two-story homes.",
      "Masonry chimneys in older homes, especially across the Northeast and Midwest, need counterflashing cut into the mortar joints, and freeze-thaw cycles crack mortar and crowns. Many newer homes have wood-framed chimney chases with metal caps that rust and leak into the framing.",
    ],
    signs: ["Stains on ceilings near a chimney or wall", "Rust streaks below a chimney chase cap", "Caulk-only joints where the roof meets a wall", "Rotted siding near the bottom of a roof-to-wall joint", "Leaks only in wind-driven rain"],
    process: [
      { title: "Inspect", body: "The roofer checks step flashing, counterflashing, kick-outs, the chimney crown or chase cap, and siding transitions." },
      { title: "Remove", body: "Shingles and siding are lifted along the joint to expose the old flashing." },
      { title: "Re-flash", body: "New step flashing, counterflashing and a kick-out are installed, layered to shed water." },
      { title: "Seal and test", body: "The joint is closed up and checked, with masonry or siding repairs coordinated if needed." },
    ],
    costFactors: ["Length of the joint", "Brick (cut-in counterflashing) vs. siding", "Chimney crown or chase cap work", "Rot repair behind the siding", "Roof pitch and height"],
    faqs: [
      { q: "Can flashing leaks be fixed with caulk?", a: "Only temporarily. Sealant breaks down in sun and freeze-thaw within a few years; layered metal flashing is the lasting fix." },
      { q: "What is kick-out flashing?", a: "A small bent piece at the bottom of a roof-to-wall joint that directs water into the gutter instead of behind the siding." },
    ],
    related: ["roof-leak-repair", "skylight-repair", "roof-repair", "fascia-soffit-repair"],
    isEmergencyCapable: false,
    glance: [
      { term: "Most missed", detail: "Kick-out flashing at roof-to-wall joints" },
      { term: "Masonry chimneys", detail: "Counterflashing cut into mortar joints" },
      { term: "Lasting fix", detail: "Layered metal flashing, not caulk" },
      { term: "Leaks show", detail: "In wind-driven rain or freeze-thaw" },
    ],
    updated: U,
  },
  {
    slug: "skylight-repair",
    name: "Skylight Repair & Replacement",
    shortName: "Skylights",
    category: "components",
    status: "PUBLISHED",
    seoTitle: "Skylight Leak Repair & Replacement",
    metaDescription:
      "Skylight leaks: failed flashing kits, cracked domes, condensation versus leaks, and replacing skylights during a roof replacement.",
    h1: "Skylight repair and replacement",
    answer:
      "Most skylight leaks come from the flashing around the unit rather than the glass. A roofer re-flashes the skylight with a manufacturer kit, or replaces an old or cracked unit, ideally during a roof replacement when the flashing is open anyway.",
    intro: [
      "Older plastic dome skylights yellow and crack under UV and hail, and many curbs were sealed with mastic that has since dried out.",
      "Water dripping from a skylight isn't always a leak. Warm, humid indoor air condenses on cold glass in winter in northern states, and humid outdoor air can condense on cool skylights in air-conditioned homes in the South, so the roofer checks both.",
    ],
    signs: ["Drips or stains around the skylight well", "Cracked, cloudy or yellowed dome", "Dried mastic around the curb", "Condensation running down the frame", "Hail damage to the dome"],
    process: [
      { title: "Diagnose", body: "Leak vs. condensation is determined, and the curb and flashing are inspected." },
      { title: "Re-flash or replace", body: "The unit is re-flashed with a proper kit, or replaced with a new skylight." },
      { title: "Integrate", body: "Underlayment, ice barrier where required, and shingles are woven back around the new flashing." },
      { title: "Finish", body: "Interior drywall repair is noted if the well was damaged." },
    ],
    costFactors: ["Re-flash vs. full replacement", "Skylight size and type (fixed, venting or tubular)", "Curb condition", "Interior well repair", "Combining with a re-roof"],
    faqs: [
      { q: "Should I replace skylights when I replace my roof?", a: "If they're more than 15 to 20 years old, usually yes. The flashing is open anyway, and a later replacement means disturbing the new roof." },
      { q: "Can I just remove a skylight?", a: "Yes. The opening can be framed in, decked and roofed over." },
    ],
    related: ["flashing-chimney-repair", "roof-leak-repair", "roof-replacement", "roof-repair"],
    isEmergencyCapable: false,
    glance: [
      { term: "Usual leak point", detail: "Flashing around the curb" },
      { term: "Also check", detail: "Condensation, especially in winter" },
      { term: "Best time to replace", detail: "During a roof replacement" },
      { term: "Old domes", detail: "Yellow and crack under UV and hail" },
    ],
    updated: U,
  },
  {
    slug: "fascia-soffit-repair",
    name: "Fascia, Soffit & Decking Repair",
    shortName: "Fascia & soffit",
    category: "components",
    status: "PUBLISHED",
    seoTitle: "Fascia, Soffit & Roof Decking Repair",
    metaDescription:
      "Rotted fascia, damaged soffit and soft roof decking: causes, repairs, animal entry points and why drip edge protects the roof edge.",
    h1: "Fascia, soffit and decking repair",
    answer:
      "Fascia boards and the roof edge rot when water gets behind gutters or there's no drip edge, and soffits are a common entry point for squirrels, rats, raccoons and birds. Repair replaces rotted wood, adds drip edge and closes openings with vented soffit so the attic still breathes.",
    intro: [
      "Rain-heavy regions and ice-dam-prone roofs both rot the roof edge: one through overflowing gutters, the other through meltwater backing up at the eaves. Wood that looks fine painted can be soft underneath, so roofers probe it before replacing the edge.",
      "Animals find gaps at soffit returns and rotted corners, then chew wiring and insulation in the attic. Closing those gaps is routine during re-roofs.",
    ],
    signs: ["Peeling paint or soft wood at the roof edge", "Gutters pulling away from the house", "Sagging or missing soffit panels", "Scratching sounds in the attic", "Soft spots felt while walking the roof"],
    process: [
      { title: "Probe and mark", body: "Fascia, rafter tails and decking are checked for rot." },
      { title: "Replace wood", body: "Rotted boards and decking are cut out and replaced." },
      { title: "Protect the edge", body: "Drip edge is installed so water drips into the gutter rather than behind it." },
      { title: "Close openings", body: "Soffit is repaired or replaced with vented panels, and entry gaps are sealed." },
    ],
    costFactors: ["Linear feet of fascia and soffit", "Wood vs. fiber cement vs. aluminum wrap", "Decking sheets replaced", "Gutter removal and reinstallation", "Painting"],
    faqs: [
      { q: "Why does fascia rot behind gutters?", a: "Without drip edge, water runs behind the gutter onto the fascia. Overflowing gutters and ice dams make it worse." },
      { q: "Will a roofer handle animal entry points?", a: "They can close soffit and roof-edge gaps. Have a wildlife service remove animals first so none are sealed inside." },
    ],
    related: ["roof-ventilation", "roof-repair", "flashing-chimney-repair", "ice-dam-removal"],
    isEmergencyCapable: false,
    glance: [
      { term: "Main cause", detail: "Missing drip edge, overflowing gutters and ice dams" },
      { term: "Also seen", detail: "Animal entry at soffit returns" },
      { term: "Material options", detail: "Wood, fiber cement or aluminum wrap" },
      { term: "Common during", detail: "Re-roofs, when the edge is exposed" },
    ],
    updated: U,
  },
];
